---
driver:
  name: vagrant

  customize:
    cpus: 2
    memory: 4096
  gui: false
  # synced_folders:
  #   - ["./", "/sources"]
  #   - ["~/chef-kits", "/chef-kits"]

provisioner:
  name: chef_zero
  log_level: info
  # require_chef_omnibus: true
  # require_chef_omnibus: 11.18.12


verifier:
  name: inspec

platforms:
  # - name: ubuntu-16.04
  # - name: centos-6.7
  # - name: centos-7.3
  - name: centos-7
  # - name: win2016
  - name: win2008r2
  # - name: tricky/solaris11-chef
  # - name: tricky/solaris10-chef

suites:
  - name: default
    run_list:
      - recipe[chef_client_manager::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chef_client:
        config:
          log_level: debug
      ohai:
        disabled_plugins: [ ]
